server:
  port: 8081

azure:
  keyvault:
    uri: https://supplier-kv.vault.azure.net/
    secret:
      property-sources-enabled: true   # <-- Required to load secrets

spring:
  datasource:
    url: jdbc:postgresql://pg-supplier-learning.postgres.database.azure.com:5432/supplierdb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: pgadmin  # ${db-username}         # <-- Loaded from Key Vault
    password: P@ssw0rd123!           # <-- Hardcoded

  sql:
    init:
      mode: always        # <â€“ Forces data.sql execution
      continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
